### ISSUE TITLE
Send data to connected device

### ISSUE THREAD

**Issue by rrrovalle** [MousyBusiness/flutter_iot_wifi#1]
It's possible to do it?

**Comment by MousyBusiness** [comment]
@rrrovalle what are you trying to sent and what is receiving?

**Comment by by90** [comment]
for example ,android, we access "http://ip/getdata", error : Network is unreachable.
and first of all , it can't connect ap, because there's not internet on ap ,you connect it,then android auto change to other wifi network....

**Comment by AniketJangam** [comment]
@MousyBusiness and @rrrovalle any updates on the Internet connectivity feature? Were you able to make it work @by90?

**Comment by MousyBusiness** [comment]
A few points, the current implementation provisions for no internet, you'll see the network capability is removed and binding is forced after connection to prevent os disconnections. If you want to provide a working sample I'll be happy to help debug your issue.

**Comment by Shresthj** [comment]
I am getting this type of error-
help me out to connect wifi (ssid, password) in mobile.

E/flutter (23119): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method connect on channel flutter_iot_wifi)
E/flutter (23119): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (23119): <asynchronous suspension>
E/flutter (23119): #1      FlutterIotWifi.connect (package:smarty/features/home/presentation/views/flutter_iot_wifi.dart:14:23)
E/flutter (23119): <asynchronous suspension>
E/flutter (23119): #2      AccessPointWidget._connect.<anonymous closure> (package:smarty/features/home/presentation/views/wifi.dart:4753:65)
E/flutter (23119): <asynchronous suspension>
E/flutter (23119):
